#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         20
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "*" state=floating sticky

bspc rule -a Gimp desktop='^8' state=floating follow=on

bspc rule -a Google-chrome desktop='^2' state=tiled follow=on
bspc rule -a Chromium desktop='^2' state=tiled follow=on
bspc rule -a firefox desktop='^2' state=tiled follow=on
bspc rule -a Chromium-browser desktop='^2' state=tiled follow=on
bspc rule -a Lxterminal state=tiled 
bspc rule -a Plank layer=normal manage=on border=off
bspc rule -a qterminal state=tiled
bspc rule -a mpv border=off

bspc config focused_border_color	\#1a2026               
bspc config normal_border_color		\#1a2026  
bspc config presel_feedback_color	\#94cf95

bspc config top_padding 34	#polybar_size + half_gap
bspc config right_padding 0
bspc config left_padding 0
bspc config bottom_padding 0

xset s off -dpms
feh --bg-fill ~/.wallpaper
polybar main &
picom --experimental-backends &
